name: Deploy Node Application

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login in docker hub 
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t hadhi2006/techunt .
      - name: Publish Image to docker hub 
        run: docker push hadhi2006/techunt:latest
  

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull hadhi2006/techunt:latest
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nodejs-app-container -e AlTAS_PASSWORD=`${{ secrets.MONG_PASSWORD }}` hadhi2006/techunt