name: Push to Master Branch

on:
  push:
    branches:
      - master  

jobs:
  push_to_master:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log message
        run: |
          echo "This workflow is triggered by a push event ."
